<?php

/**
 * Genre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Genre extends BaseGenre
{
	public static function getAll($filter = null){
		
		$q = Doctrine_Query::create()
			->select('g.id, g.name')
		    ->from('Genre g')
		    ->orderBy('g.name');
		
		if ($filter !== null){
			$joinedToAlbum = false;
			$joinedToTrack = false;
			
			if (is_array($filter)){
				foreach ($filter as $key => $val){
					if ($key === "album"){
						if (!$joinedToTrack){
							$q->leftJoin('g.Track t');
							$joinedToTrack = true;
						}
						if (!$joinedToAlbum){
							$q->leftJoin('t.Album al');
							$joinedToAlbum = true;
						}
						$q->whereIn('al.id', $val);
					}
					elseif ($key === "artist"){
						if (!$joinedToTrack){
							$q->leftJoin('g.Track t');
							$joinedToTrack = true;
						}
						if (!$joinedToAlbum){
							$q->leftJoin('t.Album al');
							$joinedToAlbum = true;
						}
						$q->leftJoin('al.Artist ar')
						  ->whereIn('ar.id', $val);
					}
					elseif ($key === "year"){
						if (!$joinedToTrack){
							$q->leftJoin('g.Track t');
							$joinedToTrack = true;
						}
						$q->whereIn('t.year', $val);
					}
				}
			}
		}
		
		return $q->fetchArray();
	}
}