<?php

/**
 * Album
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Album extends BaseAlbum
{
	public static function getAll($filter = null){
		
		$q = Doctrine_Query::create()
			->select('al.id, al.name, LEFT(t.uripath, LENGTH(t.uripath) - POSITION(\'/\' IN REVERSE(t.uripath))) as albumpath, t.year as year')
		    ->from('Album al')
			->leftJoin('al.Track t')
		    ->orderBy('al.name')
			->groupBy('t.album_id');
		
		if ($filter !== null){
			if (is_array($filter)){
				foreach ($filter as $key => $val){
				    if ($key === "album"){
				        $q->whereIn('al.id', $val);
				    }
					elseif ($key === "artist"){
						$q->leftJoin('al.Artist ar')
						  ->whereIn('ar.id', $val);
					}
					elseif ($key === "genre"){
						$q->leftJoin('t.Genre g')
						  ->whereIn('g.id', $val);
					}
					elseif ($key === "year"){
						if (!$joinedToTrack){
							$q->leftJoin('al.Track t');
							$joinedToTrack = true;
						}
						$q->whereIn('t.year', $val);
					}
				}
			}
		}
		
		return $q->fetchArray();
	}
	
	public static function getUnique(Artist $artist, $name, $insert_if_not_exists=false){
	    $q = Doctrine_Query::create()
	    ->select('al.id')
	    ->from('Album al')
	    ->where('al.name = ?', $name)
	    ->andWhere('al.artist_id = ?', $artist->id);
	    $ret = $q->fetchOne();
	    if ($insert_if_not_exists && !$ret){
	        $a = new Album();
	        $a->name = $name;
	        $a->Artist = $artist;
	        $a->save();
	        $ret = $a;
	    }
	    return $ret;
	}
}