<?php

/**
 * Track
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Track extends BaseTrack
{
	const OPT_TITLE = "Titre";
	const OPT_ARTIST = "Artiste";
	const OPT_ALBUM = "Album";
	const OPT_TRACKNO = "Piste";
	const OPT_YEAR = "Année";
	const OPT_GENRE = "Genre";
	const OPT_DURATION = "Durée";
	const OPT_FREQ = "Frequence";
	const OPT_BITRATE = "Bitrate";
	const OPT_HREF = "Href";
	const OPT_ID = "ID";
	
	private static $TAB_OPTS = array(
		"name"		=>	self::OPT_TITLE,
		"artist"	=>	self::OPT_ARTIST,
		"album"		=>	self::OPT_ALBUM,
		"trackno"	=>	self::OPT_TRACKNO,
		"year"		=>	self::OPT_YEAR,
		"genre"		=>	self::OPT_GENRE,
		"duration"	=>	self::OPT_DURATION,
		"frequency"	=>	self::OPT_FREQ,
		"bitrate"	=>	self::OPT_BITRATE,
		"uripath"	=>	self::OPT_HREF,
		"id"		=>	self::OPT_ID
	);
	private static $TAB_OPTS_WITH_PREFIX = array(
		"t_name"		=>	self::OPT_TITLE,
		"ar_artist"		=>	self::OPT_ARTIST,
		"al_album"		=>	self::OPT_ALBUM,
		"t_trackno"		=>	self::OPT_TRACKNO,
		"t_year"		=>	self::OPT_YEAR,
		"g_genre"		=>	self::OPT_GENRE,
		"t_duration"	=>	self::OPT_DURATION,
		"t_frequency"	=>	self::OPT_FREQ,
		"t_bitrate"		=>	self::OPT_BITRATE,
		"t_uripath"		=>	self::OPT_HREF,
		"t_id"			=>	self::OPT_ID
	);
	private static $INVISIBLE_OPTS = array(
		"uripath",
		"id",
		"frequency",
		"bitrate"
	);
	private static $INVISIBLE_OPTS_WITH_PREFIX = array(
		"t_uripath",
		"t_id",
		"t_frequency",
		"t_bitrate"
	);
	
	private static function checkOptions($options){
		$optionsRet = array();
		if ($options === null){
			$optionsRet = array(
				"name"		=>	self::OPT_TITLE,
				"artist"	=>	self::OPT_ARTIST,
				"album"		=>	self::OPT_ALBUM,
				"year"		=>	self::OPT_YEAR,
				"genre"		=>	self::OPT_GENRE,
				"duration"	=>	self::OPT_DURATION,
				"uripath"	=>	self::OPT_HREF,
				"id"		=>	self::OPT_ID,
				"trackno"	=>	self::OPT_TRACKNO
			);
		}else{
			foreach ($options as $key => $option){
				if (in_array($option, self::$TAB_OPTS)){
					$optionsRet[$key] = $option;
				}
			}
		}
		return $optionsRet;
	}
	
	public static function getAll($cols = null, $filter = null, $offset = 0, $limit = 100){
		$cols = Track::checkOptions($cols);
		$isJoinedToAlbum = false;
		$isJoinedToArtist = false;
		$isJoinedToGenre = false;
		$order_by = array();
		$q = Doctrine_Core::getTable('Track')
			->createQuery('t');
		
		//Options
		foreach ($cols as $key => $option){
			if ($option === self::OPT_GENRE){
				$q->addSelect('g.name as genre');
				$q->leftJoin('t.Genre g');
				$isJoinedToGenre = true;
			}
			elseif ($option === self::OPT_ALBUM){
				$q->addSelect('al.name as album');
				if ($isJoinedToAlbum === false){
					$q->leftJoin('t.Album al');
					$isJoinedToAlbum = true;
				}
			}
			elseif ($option === self::OPT_ARTIST){
				$q->addSelect('ar.name as artist');
				if ($isJoinedToAlbum === false){
					$q->leftJoin('t.Album al');
					$isJoinedToAlbum = true;
				}
				$q->leftJoin('al.Artist ar');
				$isJoinedToArtist = true;
			}
			else{
				$q->addSelect('t.'.$key.' as '.$key);
			}
		}
		
		//Filters
		if ($filter !== null){
			if (is_array($filter)){
				foreach ($filter as $key => $val){
					if ($key === "artist"){
						if (!$isJoinedToAlbum){
							$q->leftJoin('t.Album al');
							$isJoinedToAlbum = true;
						}
						if(!$isJoinedToArtist){
							$q->leftJoin('al.Artist ar');
						}
						$q->whereIn('ar.id', $val);
					}
					elseif ($key === "album"){
						if (!$isJoinedToAlbum){
							$q->leftJoin('a.Album al');	  
							$isJoinedToAlbum = true;
						}
						$q->whereIn('al.id', $val);
					}
					elseif ($key === "genre"){
						if(!$isJoinedToGenre){
							$q->leftJoin('t.Genre g');
						}
						$q->whereIn('g.id', $val);
					}
					elseif ($key === "year"){
						$q->whereIn('t.year', $val);
					}
				}
			}
		}
		$isJoinedToAlbum = false;
		$isJoinedToArtist = false;
		if ($isJoinedToArtist){
			$order_by[] = 'ar.name';
		}
		if ($isJoinedToAlbum){
			$order_by[] = 'al.name';
		}
		$order_by[] = 't.trackno';
		$q->orderBy(implode(', ', $order_by))->limit($limit)->offset($offset);
		
		return $q->execute(array(), Doctrine_Core::HYDRATE_SCALAR);
	}
	
	public static function getAllYears($filter = null){
		
		$q = Doctrine_Query::create()
			->select('DISTINCT t.year AS year')
		    ->from('Track t')
		    ->orderBy('year');
		
		if ($filter !== null){
			$joinedToAlbum = false;
			
			if (is_array($filter)){
				foreach ($filter as $key => $val){
					if ($key === "artist"){
						if (!$joinedToAlbum){
							$q->leftJoin('t.Album al');
							$joinedToAlbum = true;
						}
						$q->leftJoin('al.Artist ar')
						  ->whereIn('ar.id', $val);
					}
					elseif ($key === "genre"){
						$q->leftJoin('t.Genre g')
						  ->whereIn('g.id', $val);
					}
					elseif ($key === "album"){
						if (!$joinedToAlbum){
							$q->leftJoin('t.Album al');
							$joinedToAlbum = true;
						}
						$q->whereIn('al.id', $val);
					}
				}
			}
		}
		
		return $q->fetchArray();
	}
	
	public static function getOpts($withPrefix = false){
		if ($withPrefix === true){
			return self::$TAB_OPTS_WITH_PREFIX;
		}
		return self::$TAB_OPTS;
	}
	
	public static function isOptInvisible($opt, $withPrefix = false){
		if ($withPrefix === true){
			if (in_array($opt ,self::$INVISIBLE_OPTS_WITH_PREFIX))
				return true;
		}else{
			if (in_array($opt ,self::$INVISIBLE_OPTS))
				return true;
		}
		return false;
	}
	
	public static function getVisibleOpts($withPrefix = false, $inOrder = false){
		$array = array();
		$opts = self::getOpts($withPrefix);
		$i = 0;
		foreach($opts as $key => $opt){
			if (!self::isOptInvisible($key, $withPrefix)){
				if ($inOrder)
					$array[$key] = $i++;
				else
					$array[$key] = $opt;
			}
		}
		return $array;
	}
}